# Generated by Django 3.2 on 2021-04-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('channel', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('os', models.CharField(max_length=150, null=True)),
                ('impressions', models.IntegerField(null=True)),
                ('clicks', models.IntegerField(null=True)),
                ('installs', models.IntegerField(null=True)),
                ('spend', models.FloatField(null=True)),
                ('revenue', models.FloatField(null=True)),
            ],
        ),
    ]
